import argparse
import json
import sys
from pathlib import Path
from typing import Any

DEFAULT_MODEL = Path(
    "/home/wdj/.cache/huggingface/hub/"
    "models--Qwen--Qwen3-VL-2B-Instruct"
)

INSPECTION_PROMPT = """\
输入图像是3D Gaussian Splatting（3DGS）的渲染结果。请逐区域检查画面，然后判断是否存在明显的3D重建或渲染异常。

重点检查：
1. 是否存在天空、地面、建筑等区域大面积的未渲染空洞(渲染空洞为黑色，其余颜色不认为是空洞)；
2. 是否存在明显的几何拉伸、撕裂、重影；
3. 是否存在重复物体或不符合场景空间结构的物体；
4. 是否存在明显的Gaussian splatting伪影；
5. 整个场景在视觉和空间结构上是否合理。

判定要求：
- 正常的云、树叶、枝条、建筑结构、反射和阴影不要误判；
- 重点寻找违反真实场景空间结构的异常；
- 均匀的低清晰度、失焦、噪声、曝光或色彩变化本身不是重建失败；
- 对于小面积或对整体视觉效果影响不大的模糊、涂抹感不将其作为异常处理；
- 画面中任意一处存在大面积的空间结构异常，valid就必须为false；
- 只有逐一确认天空、建筑、地面、植被和前景都没有上述异常后，valid才可以为true；
- artifact是异常描述数组，每项应简洁说明异常类型和所在区域；没有明确异常时必须为空数组；
- severity按以下标准校准：
  * low：没有结构异常，画质良好；
  * medium：存在局部结构异常，但不影响画面的主体理解与整体结构，valid为true；
  * high：异常覆盖大面积区域或严重破坏场景结构，valid必须为false；

按左上、右上、中央、左下、右下的顺序检查，不要跳过边缘区域。
最终只输出一个合法JSON对象，不要复述任务，不要输出Markdown代码块或其他文字。
对象必须恰好包含以下字段：
- "valid"：JSON布尔值；
- "artifact"：JSON字符串数组，描述异常类型和位置；
- "severity"："low"、"medium"或"high"；
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Detect obvious 3D Gaussian Splatting artifacts in one image."
    )
    parser.add_argument("image", type=Path, help="Path to the image to inspect")
    parser.add_argument(
        "--model",
        default=str(DEFAULT_MODEL),
        help=f"Hugging Face model name or local path (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=512,
        help="Maximum number of tokens generated by the model (default: 512)",
    )
    parser.add_argument(
        "--device",
        help="Device used for inference (default: cuda:0 when available, otherwise cpu)",
    )
    return parser.parse_args()


def json_object(text: str) -> dict[str, Any]:
    """Find and decode a JSON object even if the model added surrounding text."""
    decoder = json.JSONDecoder()
    objects = []
    for index, character in enumerate(text):
        if character != "{":
            continue
        try:
            value, _ = decoder.raw_decode(text[index:])
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            objects.append(value)
    if not objects:
        raise ValueError("模型输出中没有合法的JSON对象")
    return objects[-1]


def validate_result(result: dict[str, Any]) -> dict[str, Any]:
    required_keys = {"valid", "artifact", "severity"}
    if set(result) != required_keys:
        raise ValueError("模型输出字段必须且只能是valid、artifact、severity")

    valid = result.get("valid")
    artifacts = result.get("artifact")
    severity = result.get("severity")


    if not isinstance(valid, bool):
        raise ValueError("valid必须是布尔值")
    if not isinstance(artifacts, list) or not all(
        isinstance(item, str) for item in artifacts
    ):
        raise ValueError("artifact必须是字符串数组")
    if severity not in {"low", "medium", "high"}:
        raise ValueError("severity必须是low、medium或high")
    
    return {
        "valid": valid,
        "artifact": artifacts,
        "severity": severity,
    }


def resolve_model_source(model: str | Path) -> tuple[str, bool]:
    """Resolve a Hugging Face cache root to a directly loadable snapshot."""
    requested = Path(model).expanduser()
    if not requested.exists():
        return str(model), False
    if not requested.is_dir():
        raise ValueError(f"模型路径不是目录：{requested}")

    direct = requested.resolve()
    if (direct / "config.json").is_file():
        return str(direct), True

    candidates: list[Path] = []
    main_ref = direct / "refs" / "main"
    if main_ref.is_file():
        revision = main_ref.read_text(encoding="utf-8").strip()
        if revision and "/" not in revision and "\\" not in revision:
            candidates.append(direct / "snapshots" / revision)
    snapshots = direct / "snapshots"
    if snapshots.is_dir():
        candidates.extend(
            sorted(
                (path for path in snapshots.iterdir() if path.is_dir()),
                key=lambda path: path.stat().st_mtime,
                reverse=True,
            )
        )

    seen: set[Path] = set()
    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved in seen:
            continue
        seen.add(resolved)
        has_weights = (resolved / "model.safetensors").is_file() or (
            resolved / "model.safetensors.index.json"
        ).is_file()
        if (resolved / "config.json").is_file() and has_weights:
            return str(resolved), True
    raise ValueError(f"模型缓存中没有完整的可加载snapshot：{direct}")


def main() -> int:
    args = parse_args()
    image_path = args.image.expanduser().resolve()

    if not image_path.is_file():
        print(f"错误：图片不存在或不是文件：{image_path}", file=sys.stderr)
        return 2
    if args.max_new_tokens <= 0:
        print("错误：--max-new-tokens必须大于0", file=sys.stderr)
        return 2

    messages = [
        {
            "role": "system",
            "content": (
                "你是严谨的3DGS渲染质量检测器。必须依据输入图像本身判断，"
                "不得套用固定答案或默认判定为正常。"
            ),
        },
        {
            "role": "user",
            "content": [
                {"type": "image", "url": str(image_path)},
                {"type": "text", "text": INSPECTION_PROMPT},
            ],
        }
    ]

    try:
        from copy import deepcopy

        import torch
        from transformers import AutoModelForImageTextToText, AutoProcessor

        model_source, local_files_only = resolve_model_source(args.model)
        processor = AutoProcessor.from_pretrained(
            model_source,
            local_files_only=local_files_only,
        )
        device = args.device or ("cuda:0" if torch.cuda.is_available() else "cpu")
        model = AutoModelForImageTextToText.from_pretrained(
            model_source,
            local_files_only=local_files_only,
            device_map=device,
            dtype="auto",
        )
        inputs = processor.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True,
            return_dict=True,
            return_tensors="pt",
        )
        inputs = inputs.to(model.device)

        generation_config = deepcopy(model.generation_config)
        generation_config.max_new_tokens = args.max_new_tokens
        generation_config.max_length = None
        generation_config.do_sample = False
        generation_config.temperature = 1.0
        generation_config.top_p = 1.0
        generation_config.top_k = 50
        generation_config.return_dict_in_generate = False

        generated_ids = model.generate(
            **inputs,
            generation_config=generation_config,
        )
        prompt_length = inputs["input_ids"].shape[1]
        generated_text = processor.batch_decode(
            generated_ids[:, prompt_length:],
            skip_special_tokens=True,
            clean_up_tokenization_spaces=False,
        )[0]
        result = validate_result(json_object(generated_text))
    except Exception as exc:
        print(f"检测失败：{exc}", file=sys.stderr)
        return 1

    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
